# Generated by Django 5.0.1 on 2026-01-27 23:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellido')),
                ('is_owner', models.BooleanField(default=False, help_text='Indica si el usuario es propietario de un negocio', verbose_name='Es Propietario')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Negocio')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Negocio')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Negocio')),
                ('schedule_config', models.JSONField(default=dict, help_text='Configuración de horarios de atención por día de la semana', verbose_name='Configuración de Horarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('owner', models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración del servicio en minutos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Hora de Fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la cita', null=True, verbose_name='Notas')),
                ('is_block', models.BooleanField(default=False, help_text='Si está marcado, este horario está bloqueado y no disponible para clientes', verbose_name='Es Bloqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.business', verbose_name='Negocio')),
                ('service', models.ForeignKey(blank=True, help_text='Opcional para bloqueos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['business', 'start_time'], name='core_appoin_busines_d72e17_idx'), models.Index(fields=['client', 'start_time'], name='core_appoin_client__aa5d1b_idx'), models.Index(fields=['status'], name='core_appoin_status_e978b8_idx')],
            },
        ),
    ]
