# Generated by Django 5.0.1 on 2026-01-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='America/Monterrey', help_text='Zona horaria del negocio (ej: America/Monterrey, America/Mexico_City)', max_length=50, verbose_name='Zona Horaria'),
        ),
    ]
