# Generated by Django 5.0.1 on 2026-01-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, help_text='Breve historia o descripción del negocio para la landing page', null=True, verbose_name='Descripción del Negocio'),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Facebook', null=True, verbose_name='URL de Facebook'),
        ),
        migrations.AddField(
            model_name='business',
            name='gallery_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes de trabajos realizados (formato JSON array)', verbose_name='Galería de Imágenes'),
        ),
        migrations.AddField(
            model_name='business',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen principal para la sección hero', null=True, verbose_name='URL de Imagen Hero'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Instagram', null=True, verbose_name='URL de Instagram'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo del negocio', null=True, verbose_name='URL del Logo'),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Color de marca en formato hexadecimal (ej: #000000)', max_length=7, verbose_name='Color Principal'),
        ),
    ]
