# Generated by Django 5.0.1 on 2026-01-28 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_business_description_business_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen de trabajo realizado', upload_to='gallery/%Y/%m/%d/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=200, null=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
