# Generated by Django 5.0.1 on 2026-01-28 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Número de barberos o estaciones disponibles simultáneamente', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad'),
        ),
    ]
